name: Build VSCode Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: npm i -g vsce && mkdir dist
    - name: Build the VSCode Extension Package
      run: vsce package --out dist
    - name: FTP Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: admin.jojojux.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/files.jojojux.de/resources/builds/custom-achievements-plugin-vscode/
        local-dir: ./dist/
    - uses: actions/upload-artifact@v3
      with:
        name: VSCode Extension
        path: "./dist/*.vsix"
