name: Build VSCode Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install vsce
      run: npm i -g vsce
    - name: Build the VSCode Extension Package
      run: vsce package --out ./builds/
    - name: FTP Upload
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: admin.jojojux.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/files.jojojux.de/resources/builds/custom-achievements-plugin-vscode/
        local-dir: ./builds/
    - uses: actions/upload-artifact@v3
      with:
        name: VSCode Extension
        path: "./builds/*.vsix"
