name: Build VSCode Extension

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: npm i && npm i -g -U @vscode/vsce && mkdir dist
    - name: Build the VSCode Extension Package
      run: vsce package --out dist
    - name: FTP Upload
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: 212.227.8.25
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./dist
        remoteDir: /www/files.jojojux.de/resources/builds/custom-achievements-plugin-vscode
    - uses: actions/upload-artifact@v3
      with:
        name: VSCode Extension
        path: "./dist/*.vsix"
